// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.PlacaArduino;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect PlacaArduino_Roo_Jpa_Entity {
    
    declare @type: PlacaArduino: @Entity;
    
    declare @type: PlacaArduino: @Table(schema = "pfc_schema", name = "placa_arduino");
    
}
