// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.web;

import ad.uda.pfc.web.CaracteristicaBean;
import java.io.Serializable;

privileged aspect CaracteristicaBean_Roo_Serializable {
    
    declare parents: CaracteristicaBean implements Serializable;
    
    private static final long CaracteristicaBean.serialVersionUID = 1L;
    
}
