// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.web;

import ad.uda.pfc.web.HabitacleBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect HabitacleBean_Roo_Configurable {
    
    declare @type: HabitacleBean: @Configurable;
    
}
