// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.web;

import ad.uda.pfc.web.MagnitudBean;
import java.io.Serializable;

privileged aspect MagnitudBean_Roo_Serializable {
    
    declare parents: MagnitudBean implements Serializable;
    
    private static final long MagnitudBean.serialVersionUID = 1L;
    
}
