// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.web;

import ad.uda.pfc.web.TipusSensorBean;
import java.io.Serializable;

privileged aspect TipusSensorBean_Roo_Serializable {
    
    declare parents: TipusSensorBean implements Serializable;
    
    private static final long TipusSensorBean.serialVersionUID = 1L;
    
}
