// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.web.converter;

import ad.uda.pfc.web.converter.MagnitudConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MagnitudConverter_Roo_Configurable {
    
    declare @type: MagnitudConverter: @Configurable;
    
}
