// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.Caracteristica;
import ad.uda.pfc.domain.CaracteristicaDataOnDemand;
import ad.uda.pfc.domain.CaracteristicaIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CaracteristicaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CaracteristicaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CaracteristicaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CaracteristicaIntegrationTest: @Transactional;
    
    @Autowired
    private CaracteristicaDataOnDemand CaracteristicaIntegrationTest.dod;
    
    @Test
    public void CaracteristicaIntegrationTest.testCountCaracteristicas() {
        Assert.assertNotNull("Data on demand for 'Caracteristica' failed to initialize correctly", dod.getRandomCaracteristica());
        long count = Caracteristica.countCaracteristicas();
        Assert.assertTrue("Counter for 'Caracteristica' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CaracteristicaIntegrationTest.testFindCaracteristica() {
        Caracteristica obj = dod.getRandomCaracteristica();
        Assert.assertNotNull("Data on demand for 'Caracteristica' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Caracteristica' failed to provide an identifier", id);
        obj = Caracteristica.findCaracteristica(id);
        Assert.assertNotNull("Find method for 'Caracteristica' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Caracteristica' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CaracteristicaIntegrationTest.testFindAllCaracteristicas() {
        Assert.assertNotNull("Data on demand for 'Caracteristica' failed to initialize correctly", dod.getRandomCaracteristica());
        long count = Caracteristica.countCaracteristicas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Caracteristica', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Caracteristica> result = Caracteristica.findAllCaracteristicas();
        Assert.assertNotNull("Find all method for 'Caracteristica' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Caracteristica' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CaracteristicaIntegrationTest.testFindCaracteristicaEntries() {
        Assert.assertNotNull("Data on demand for 'Caracteristica' failed to initialize correctly", dod.getRandomCaracteristica());
        long count = Caracteristica.countCaracteristicas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Caracteristica> result = Caracteristica.findCaracteristicaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Caracteristica' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Caracteristica' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CaracteristicaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Caracteristica' failed to initialize correctly", dod.getRandomCaracteristica());
        Caracteristica obj = dod.getNewTransientCaracteristica(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Caracteristica' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Caracteristica' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Caracteristica' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CaracteristicaIntegrationTest.testRemove() {
        Caracteristica obj = dod.getRandomCaracteristica();
        Assert.assertNotNull("Data on demand for 'Caracteristica' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Caracteristica' failed to provide an identifier", id);
        obj = Caracteristica.findCaracteristica(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Caracteristica' with identifier '" + id + "'", Caracteristica.findCaracteristica(id));
    }
    
}
