// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.HabitacleIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect HabitacleIntegrationTest_Roo_Configurable {
    
    declare @type: HabitacleIntegrationTest: @Configurable;
    
}
