// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.HabitacleDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect HabitacleDataOnDemand_Roo_Configurable {
    
    declare @type: HabitacleDataOnDemand: @Configurable;
    
}
