// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.Magnitud;
import ad.uda.pfc.domain.MagnitudDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect MagnitudDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MagnitudDataOnDemand: @Component;
    
    private Random MagnitudDataOnDemand.rnd = new SecureRandom();
    
    private List<Magnitud> MagnitudDataOnDemand.data;
    
    public Magnitud MagnitudDataOnDemand.getNewTransientMagnitud(int index) {
        Magnitud obj = new Magnitud();
        setNom(obj, index);
        setSimbol(obj, index);
        return obj;
    }
    
    public void MagnitudDataOnDemand.setNom(Magnitud obj, int index) {
        String nom = "nom_" + index;
        if (nom.length() > 250) {
            nom = nom.substring(0, 250);
        }
        obj.setNom(nom);
    }
    
    public void MagnitudDataOnDemand.setSimbol(Magnitud obj, int index) {
        String simbol = "simbol_" + index;
        if (simbol.length() > 10) {
            simbol = simbol.substring(0, 10);
        }
        obj.setSimbol(simbol);
    }
    
    public Magnitud MagnitudDataOnDemand.getSpecificMagnitud(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Magnitud obj = data.get(index);
        Integer id = obj.getId();
        return Magnitud.findMagnitud(id);
    }
    
    public Magnitud MagnitudDataOnDemand.getRandomMagnitud() {
        init();
        Magnitud obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Magnitud.findMagnitud(id);
    }
    
    public boolean MagnitudDataOnDemand.modifyMagnitud(Magnitud obj) {
        return false;
    }
    
    public void MagnitudDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Magnitud.findMagnitudEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Magnitud' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Magnitud>();
        for (int i = 0; i < 10; i++) {
            Magnitud obj = getNewTransientMagnitud(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
