// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.Magnitud;
import ad.uda.pfc.domain.MagnitudDataOnDemand;
import ad.uda.pfc.domain.MagnitudIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MagnitudIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MagnitudIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MagnitudIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MagnitudIntegrationTest: @Transactional;
    
    @Autowired
    private MagnitudDataOnDemand MagnitudIntegrationTest.dod;
    
    @Test
    public void MagnitudIntegrationTest.testCountMagnituds() {
        Assert.assertNotNull("Data on demand for 'Magnitud' failed to initialize correctly", dod.getRandomMagnitud());
        long count = Magnitud.countMagnituds();
        Assert.assertTrue("Counter for 'Magnitud' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MagnitudIntegrationTest.testFindMagnitud() {
        Magnitud obj = dod.getRandomMagnitud();
        Assert.assertNotNull("Data on demand for 'Magnitud' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Magnitud' failed to provide an identifier", id);
        obj = Magnitud.findMagnitud(id);
        Assert.assertNotNull("Find method for 'Magnitud' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Magnitud' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MagnitudIntegrationTest.testFindAllMagnituds() {
        Assert.assertNotNull("Data on demand for 'Magnitud' failed to initialize correctly", dod.getRandomMagnitud());
        long count = Magnitud.countMagnituds();
        Assert.assertTrue("Too expensive to perform a find all test for 'Magnitud', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Magnitud> result = Magnitud.findAllMagnituds();
        Assert.assertNotNull("Find all method for 'Magnitud' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Magnitud' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MagnitudIntegrationTest.testFindMagnitudEntries() {
        Assert.assertNotNull("Data on demand for 'Magnitud' failed to initialize correctly", dod.getRandomMagnitud());
        long count = Magnitud.countMagnituds();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Magnitud> result = Magnitud.findMagnitudEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Magnitud' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Magnitud' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MagnitudIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Magnitud' failed to initialize correctly", dod.getRandomMagnitud());
        Magnitud obj = dod.getNewTransientMagnitud(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Magnitud' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Magnitud' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Magnitud' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MagnitudIntegrationTest.testRemove() {
        Magnitud obj = dod.getRandomMagnitud();
        Assert.assertNotNull("Data on demand for 'Magnitud' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Magnitud' failed to provide an identifier", id);
        obj = Magnitud.findMagnitud(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Magnitud' with identifier '" + id + "'", Magnitud.findMagnitud(id));
    }
    
}
