// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.PinArduino;
import ad.uda.pfc.domain.PinArduinoDataOnDemand;
import ad.uda.pfc.domain.PlacaArduinoDataOnDemand;
import ad.uda.pfc.domain.SensorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PinArduinoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PinArduinoDataOnDemand: @Component;
    
    private Random PinArduinoDataOnDemand.rnd = new SecureRandom();
    
    private List<PinArduino> PinArduinoDataOnDemand.data;
    
    @Autowired
    private PlacaArduinoDataOnDemand PinArduinoDataOnDemand.placaArduinoDataOnDemand;
    
    @Autowired
    private SensorDataOnDemand PinArduinoDataOnDemand.sensorDataOnDemand;
    
    public PinArduino PinArduinoDataOnDemand.getNewTransientPinArduino(int index) {
        PinArduino obj = new PinArduino();
        setNumPin(obj, index);
        return obj;
    }
    
    public void PinArduinoDataOnDemand.setNumPin(PinArduino obj, int index) {
        Integer numPin = new Integer(index);
        obj.setNumPin(numPin);
    }
    
    public PinArduino PinArduinoDataOnDemand.getSpecificPinArduino(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PinArduino obj = data.get(index);
        Integer id = obj.getId();
        return PinArduino.findPinArduino(id);
    }
    
    public PinArduino PinArduinoDataOnDemand.getRandomPinArduino() {
        init();
        PinArduino obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return PinArduino.findPinArduino(id);
    }
    
    public boolean PinArduinoDataOnDemand.modifyPinArduino(PinArduino obj) {
        return false;
    }
    
    public void PinArduinoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PinArduino.findPinArduinoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PinArduino' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PinArduino>();
        for (int i = 0; i < 10; i++) {
            PinArduino obj = getNewTransientPinArduino(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
