// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.PinArduino;
import ad.uda.pfc.domain.PinArduinoDataOnDemand;
import ad.uda.pfc.domain.PinArduinoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PinArduinoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PinArduinoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PinArduinoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PinArduinoIntegrationTest: @Transactional;
    
    @Autowired
    private PinArduinoDataOnDemand PinArduinoIntegrationTest.dod;
    
    @Test
    public void PinArduinoIntegrationTest.testCountPinArduinoes() {
        Assert.assertNotNull("Data on demand for 'PinArduino' failed to initialize correctly", dod.getRandomPinArduino());
        long count = PinArduino.countPinArduinoes();
        Assert.assertTrue("Counter for 'PinArduino' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PinArduinoIntegrationTest.testFindPinArduino() {
        PinArduino obj = dod.getRandomPinArduino();
        Assert.assertNotNull("Data on demand for 'PinArduino' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PinArduino' failed to provide an identifier", id);
        obj = PinArduino.findPinArduino(id);
        Assert.assertNotNull("Find method for 'PinArduino' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PinArduino' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PinArduinoIntegrationTest.testFindAllPinArduinoes() {
        Assert.assertNotNull("Data on demand for 'PinArduino' failed to initialize correctly", dod.getRandomPinArduino());
        long count = PinArduino.countPinArduinoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'PinArduino', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PinArduino> result = PinArduino.findAllPinArduinoes();
        Assert.assertNotNull("Find all method for 'PinArduino' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PinArduino' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PinArduinoIntegrationTest.testFindPinArduinoEntries() {
        Assert.assertNotNull("Data on demand for 'PinArduino' failed to initialize correctly", dod.getRandomPinArduino());
        long count = PinArduino.countPinArduinoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PinArduino> result = PinArduino.findPinArduinoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PinArduino' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PinArduino' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PinArduinoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PinArduino' failed to initialize correctly", dod.getRandomPinArduino());
        PinArduino obj = dod.getNewTransientPinArduino(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PinArduino' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PinArduino' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'PinArduino' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PinArduinoIntegrationTest.testRemove() {
        PinArduino obj = dod.getRandomPinArduino();
        Assert.assertNotNull("Data on demand for 'PinArduino' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PinArduino' failed to provide an identifier", id);
        obj = PinArduino.findPinArduino(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PinArduino' with identifier '" + id + "'", PinArduino.findPinArduino(id));
    }
    
}
