// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.PlacaArduino;
import ad.uda.pfc.domain.PlacaArduinoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PlacaArduinoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PlacaArduinoDataOnDemand: @Component;
    
    private Random PlacaArduinoDataOnDemand.rnd = new SecureRandom();
    
    private List<PlacaArduino> PlacaArduinoDataOnDemand.data;
    
    public PlacaArduino PlacaArduinoDataOnDemand.getNewTransientPlacaArduino(int index) {
        PlacaArduino obj = new PlacaArduino();
        setDescripcio(obj, index);
        setNom(obj, index);
        setVersio(obj, index);
        return obj;
    }
    
    public void PlacaArduinoDataOnDemand.setDescripcio(PlacaArduino obj, int index) {
        String descripcio = "descripcio_" + index;
        if (descripcio.length() > 250) {
            descripcio = descripcio.substring(0, 250);
        }
        obj.setDescripcio(descripcio);
    }
    
    public void PlacaArduinoDataOnDemand.setNom(PlacaArduino obj, int index) {
        String nom = "nom_" + index;
        obj.setNom(nom);
    }
    
    public void PlacaArduinoDataOnDemand.setVersio(PlacaArduino obj, int index) {
        String versio = "versio_" + index;
        obj.setVersio(versio);
    }
    
    public PlacaArduino PlacaArduinoDataOnDemand.getSpecificPlacaArduino(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PlacaArduino obj = data.get(index);
        Integer id = obj.getId();
        return PlacaArduino.findPlacaArduino(id);
    }
    
    public PlacaArduino PlacaArduinoDataOnDemand.getRandomPlacaArduino() {
        init();
        PlacaArduino obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return PlacaArduino.findPlacaArduino(id);
    }
    
    public boolean PlacaArduinoDataOnDemand.modifyPlacaArduino(PlacaArduino obj) {
        return false;
    }
    
    public void PlacaArduinoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PlacaArduino.findPlacaArduinoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PlacaArduino' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PlacaArduino>();
        for (int i = 0; i < 10; i++) {
            PlacaArduino obj = getNewTransientPlacaArduino(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
