// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.PlacaArduino;
import ad.uda.pfc.domain.PlacaArduinoDataOnDemand;
import ad.uda.pfc.domain.PlacaArduinoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PlacaArduinoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PlacaArduinoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PlacaArduinoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PlacaArduinoIntegrationTest: @Transactional;
    
    @Autowired
    private PlacaArduinoDataOnDemand PlacaArduinoIntegrationTest.dod;
    
    @Test
    public void PlacaArduinoIntegrationTest.testCountPlacaArduinoes() {
        Assert.assertNotNull("Data on demand for 'PlacaArduino' failed to initialize correctly", dod.getRandomPlacaArduino());
        long count = PlacaArduino.countPlacaArduinoes();
        Assert.assertTrue("Counter for 'PlacaArduino' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PlacaArduinoIntegrationTest.testFindPlacaArduino() {
        PlacaArduino obj = dod.getRandomPlacaArduino();
        Assert.assertNotNull("Data on demand for 'PlacaArduino' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PlacaArduino' failed to provide an identifier", id);
        obj = PlacaArduino.findPlacaArduino(id);
        Assert.assertNotNull("Find method for 'PlacaArduino' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PlacaArduino' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PlacaArduinoIntegrationTest.testFindAllPlacaArduinoes() {
        Assert.assertNotNull("Data on demand for 'PlacaArduino' failed to initialize correctly", dod.getRandomPlacaArduino());
        long count = PlacaArduino.countPlacaArduinoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'PlacaArduino', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PlacaArduino> result = PlacaArduino.findAllPlacaArduinoes();
        Assert.assertNotNull("Find all method for 'PlacaArduino' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PlacaArduino' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PlacaArduinoIntegrationTest.testFindPlacaArduinoEntries() {
        Assert.assertNotNull("Data on demand for 'PlacaArduino' failed to initialize correctly", dod.getRandomPlacaArduino());
        long count = PlacaArduino.countPlacaArduinoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PlacaArduino> result = PlacaArduino.findPlacaArduinoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PlacaArduino' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PlacaArduino' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PlacaArduinoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PlacaArduino' failed to initialize correctly", dod.getRandomPlacaArduino());
        PlacaArduino obj = dod.getNewTransientPlacaArduino(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PlacaArduino' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PlacaArduino' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'PlacaArduino' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PlacaArduinoIntegrationTest.testRemove() {
        PlacaArduino obj = dod.getRandomPlacaArduino();
        Assert.assertNotNull("Data on demand for 'PlacaArduino' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PlacaArduino' failed to provide an identifier", id);
        obj = PlacaArduino.findPlacaArduino(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PlacaArduino' with identifier '" + id + "'", PlacaArduino.findPlacaArduino(id));
    }
    
}
