// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.Sensor;
import ad.uda.pfc.domain.SensorDataOnDemand;
import ad.uda.pfc.domain.SensorIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SensorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SensorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SensorIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SensorIntegrationTest: @Transactional;
    
    @Autowired
    private SensorDataOnDemand SensorIntegrationTest.dod;
    
    @Test
    public void SensorIntegrationTest.testCountSensors() {
        Assert.assertNotNull("Data on demand for 'Sensor' failed to initialize correctly", dod.getRandomSensor());
        long count = Sensor.countSensors();
        Assert.assertTrue("Counter for 'Sensor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SensorIntegrationTest.testFindSensor() {
        Sensor obj = dod.getRandomSensor();
        Assert.assertNotNull("Data on demand for 'Sensor' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sensor' failed to provide an identifier", id);
        obj = Sensor.findSensor(id);
        Assert.assertNotNull("Find method for 'Sensor' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Sensor' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SensorIntegrationTest.testFindAllSensors() {
        Assert.assertNotNull("Data on demand for 'Sensor' failed to initialize correctly", dod.getRandomSensor());
        long count = Sensor.countSensors();
        Assert.assertTrue("Too expensive to perform a find all test for 'Sensor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Sensor> result = Sensor.findAllSensors();
        Assert.assertNotNull("Find all method for 'Sensor' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Sensor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SensorIntegrationTest.testFindSensorEntries() {
        Assert.assertNotNull("Data on demand for 'Sensor' failed to initialize correctly", dod.getRandomSensor());
        long count = Sensor.countSensors();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Sensor> result = Sensor.findSensorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Sensor' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Sensor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SensorIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Sensor' failed to initialize correctly", dod.getRandomSensor());
        Sensor obj = dod.getNewTransientSensor(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Sensor' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Sensor' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Sensor' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SensorIntegrationTest.testRemove() {
        Sensor obj = dod.getRandomSensor();
        Assert.assertNotNull("Data on demand for 'Sensor' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sensor' failed to provide an identifier", id);
        obj = Sensor.findSensor(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Sensor' with identifier '" + id + "'", Sensor.findSensor(id));
    }
    
}
