// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.TipusSensor;
import ad.uda.pfc.domain.TipusSensorDataOnDemand;
import ad.uda.pfc.domain.TipusSensorIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TipusSensorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TipusSensorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TipusSensorIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TipusSensorIntegrationTest: @Transactional;
    
    @Autowired
    private TipusSensorDataOnDemand TipusSensorIntegrationTest.dod;
    
    @Test
    public void TipusSensorIntegrationTest.testCountTipusSensors() {
        Assert.assertNotNull("Data on demand for 'TipusSensor' failed to initialize correctly", dod.getRandomTipusSensor());
        long count = TipusSensor.countTipusSensors();
        Assert.assertTrue("Counter for 'TipusSensor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TipusSensorIntegrationTest.testFindTipusSensor() {
        TipusSensor obj = dod.getRandomTipusSensor();
        Assert.assertNotNull("Data on demand for 'TipusSensor' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipusSensor' failed to provide an identifier", id);
        obj = TipusSensor.findTipusSensor(id);
        Assert.assertNotNull("Find method for 'TipusSensor' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TipusSensor' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TipusSensorIntegrationTest.testFindAllTipusSensors() {
        Assert.assertNotNull("Data on demand for 'TipusSensor' failed to initialize correctly", dod.getRandomTipusSensor());
        long count = TipusSensor.countTipusSensors();
        Assert.assertTrue("Too expensive to perform a find all test for 'TipusSensor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TipusSensor> result = TipusSensor.findAllTipusSensors();
        Assert.assertNotNull("Find all method for 'TipusSensor' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TipusSensor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TipusSensorIntegrationTest.testFindTipusSensorEntries() {
        Assert.assertNotNull("Data on demand for 'TipusSensor' failed to initialize correctly", dod.getRandomTipusSensor());
        long count = TipusSensor.countTipusSensors();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TipusSensor> result = TipusSensor.findTipusSensorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TipusSensor' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TipusSensor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TipusSensorIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TipusSensor' failed to initialize correctly", dod.getRandomTipusSensor());
        TipusSensor obj = dod.getNewTransientTipusSensor(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TipusSensor' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TipusSensor' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TipusSensor' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TipusSensorIntegrationTest.testRemove() {
        TipusSensor obj = dod.getRandomTipusSensor();
        Assert.assertNotNull("Data on demand for 'TipusSensor' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipusSensor' failed to provide an identifier", id);
        obj = TipusSensor.findTipusSensor(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TipusSensor' with identifier '" + id + "'", TipusSensor.findTipusSensor(id));
    }
    
}
