// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ad.uda.pfc.domain;

import ad.uda.pfc.domain.TipusSensor;
import ad.uda.pfc.domain.TipusSensorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TipusSensorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TipusSensorDataOnDemand: @Component;
    
    private Random TipusSensorDataOnDemand.rnd = new SecureRandom();
    
    private List<TipusSensor> TipusSensorDataOnDemand.data;
    
    public TipusSensor TipusSensorDataOnDemand.getNewTransientTipusSensor(int index) {
        TipusSensor obj = new TipusSensor();
        setNom(obj, index);
        return obj;
    }
    
    public void TipusSensorDataOnDemand.setNom(TipusSensor obj, int index) {
        String nom = "nom_" + index;
        if (nom.length() > 250) {
            nom = nom.substring(0, 250);
        }
        obj.setNom(nom);
    }
    
    public TipusSensor TipusSensorDataOnDemand.getSpecificTipusSensor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TipusSensor obj = data.get(index);
        Integer id = obj.getId();
        return TipusSensor.findTipusSensor(id);
    }
    
    public TipusSensor TipusSensorDataOnDemand.getRandomTipusSensor() {
        init();
        TipusSensor obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return TipusSensor.findTipusSensor(id);
    }
    
    public boolean TipusSensorDataOnDemand.modifyTipusSensor(TipusSensor obj) {
        return false;
    }
    
    public void TipusSensorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TipusSensor.findTipusSensorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TipusSensor' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TipusSensor>();
        for (int i = 0; i < 10; i++) {
            TipusSensor obj = getNewTransientTipusSensor(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
